Repository TeamBehance/Behance-iOS, pull requests merged in 2022-05, with the labels that each got.

#6 [Feat] 프로젝트 에디터 UI
  Behance-iOS/Behance-iOS.xcodeproj/project.pbxproj
  Behance-iOS/Behance-iOS/Info.plist
  Behance-iOS/Behance-iOS/Source/Scenes/AddProject/AddProject.storyboard
  Behance-iOS/Behance-iOS/Source/Scenes/AddProject/AddProjectViewController.swift
  Behance-iOS/Behance-iOS/Source/Scenes/AddProject/Cells/PhotoCollectionViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/AddProject/EditorBackgroundView.swift
Labels: 인우, Pull Request

#7 [Feat] 마이페이지 UI
  Behance-iOS/Behance-iOS.xcodeproj/project.pbxproj
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/Cells/MyPageTaskCollectionViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/MyPage.storyboard
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/MyPageProjectViewController.swift
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/MyPageViewController.swift
Labels: feat, 혜수

#9 [FEAT] 홈 화면 UI
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/FeedTableViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/FeedTableViewCell.xib
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/StoryCollectionViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/StoryCollectionViewCell.xib
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/storyTableViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Cells/storyTableViewCell.xib
  Behance-iOS/Behance-iOS/Source/Scenes/Home/DataModel/FeedDataModel.swift
  Behance-iOS/Behance-iOS/Source/Scenes/Home/DataModel/StoryDataModel.swift
  Behance-iOS/Behance-iOS/Source/Scenes/Home/Home.storyboard
  Behance-iOS/Behance-iOS/Source/Scenes/Home/HomeViewController.swift
Labels: 윤서, Pull Request

#10 feat: #3 하단 컬렉션뷰 스크롤시 타이틀 UI변경
  Behance-iOS/Behance-iOS.xcodeproj/project.pbxproj
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/Cells/MyPageTitleCollectionViewCell.swift
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/MyPage.storyboard
  Behance-iOS/Behance-iOS/Source/Scenes/MyPage/MyPageViewController.swift
Labels: 혜수, Pull Request
